# "THE BEER/MATE-WARE LICENSE":
# <xil@xil.se> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy us a ( > 0 ) beer/mate in return - The Xil TEAM

# local build configurations
-include local.mk

# unset VERBOSE to turn on verbosity
VERBOSE = @

# name of binary
ELF = ledmatrix

# source files
src = ledmatrix.c \
      drivers/ws2801.c

include common.mk
